language: minimal

os:
  - osx
  - linux

before_install:
  - export PATH=$HOME/.deno/bin:$PATH

install:
  - curl -L https://deno.land/x/install/install.py | python

script:
  - deno -v
  - mkdir tmp
  - deno --allow-run --allow-env test/test-task.ts --cwd=test all | tee tmp/result
  - deno --allow-run --allow-env test/test.ts
  - deno --allow-run --allow-env example/example.ts --cwd=example all
